### ISSUE TITLE
A/B tests are broken

### ISSUE THREAD

**Issue by crusaderky** [coiled/benchmarks#757]
Since dask/distributed#7564, A/B tests have stopped working.
All workflows fail with an obscure CancellledError.

[EDIT] the below analysis is incorrect. Read more in the post below.

> The reason is that the template A/B recipe looks like this:
```yaml

channels:
  - conda-forge
dependencies:
  - python=3.9
  - coiled-runtime=0.2.1
  - pip:
    - dask==2023.3.2
    - git+https://github.com/dask/distributed@54941387cb58b279a63dcb556ae6448789860118
```
> The above first installs dask and distributed 2022.11.0 from conda and then uses pip to upgrade them.
> This was always a hack, officially supported by neither conda nor pip, and now it broke.
